### ISSUE TITLE
Playwright is NOT automatically installed as a dependency

### ISSUE THREAD

**Issue by pigiuz** [mzxrai/mcp-webresearch#2]
It looks like Playwright is not automatically installed as a dependency.
When I run claude after installing the mcp I get this error.

`Error executing code: MCP error -32603: browserType.launch: Executable doesn't exist at /Users/<myusername>/Library/Caches/ms-playwright/chromium_headless_shell-1148/chrome-mac/headless_shell
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝`

I tried to install playwright (npx playwright install) but still it doesn't work, tailing Claude's logs I get a consistent timeout error.

I tried to setup the development environment and follow your runbook, but pnpm cannot resolve path, fs, and os (it looks it's a missing package) so pnpm install fails.

not sure where to go from here

**Comment by mzxrai** [comment]
Hi, thanks for your report! I'm pushing a fix for the issue where the playwright browser binaries are not auto-installed. For the other issue, I think that may be due to Google pages having a different format outside the U.S. Will need to do some deeper research to see how we can handle that.

**Comment by mzxrai** [comment]
@pigiuz If you like, please try the latest version to see if it works better?

Here's what you'll update your config file to:

```json
{
  "mcpServers": {
    "webresearch": {
      "command": "npx",
      "args": ["-y", "@mzxrai/mcp-webresearch@latest"]
    }
  }
}
```

Notice the "@latest" part; that's what matters.

**Comment by pigiuz** [comment]
@mzxrai nope, it still doesn't work. different error this time, the server doesn't connect.
<img width="385" alt="Screenshot 2024-12-16 at 14 53 04" src="https://github.com/user-attachments/assets/bca55516-11a2-4c43-85fc-5e46cb44b1f6" />

I tried to delete the whole ~/.npm folder and left this MCP as the only one in the claude_desktop_config.json (so to avoid any clash with any other mcp).
I launched Claude and the connection timed out.
Playwright was not installed in .npm (my guess is that given it's a chunky dependency the server timed out while installing the browsers).

So I installed playwright manually `npx playwright install` and restarted claude 👈 THIS TIME THE MCP SERVER CONNECTED!!! 🥳.... BUT

I tried it out and I got very weird messages like it wasn't inspecting google 

`Call log:
  - attempting click action
    2 × waiting for element to be visible, enabled and stable
      - element is visible, enabled and stable
      - scrolling into view if needed
      - done scrolling
      - <li class="gowsYd v8Bpfb">Measure audience engagement and site statistics t…</li> from <div class="Fgvgjc">…</div> subtree intercepts pointer events
    - retrying click action
    - waiting 20ms
    2 × waiting for element to be visible, enabled and stable
      - element is visible, enabled and stable
      - scrolling into view if needed
      - done scrolling
      - <li class="gowsYd v8Bpfb">Measure audience engagement and site statistics t…</li> from <div class="Fgvgjc">…</div> subtree intercepts pointer events
    - retrying click action
      - waiting 100ms
    57 × waiting for element to be visible, enabled and stable
       - element is visible, enabled and stable
       - scrolling into view if needed
       - done scrolling
       - <li class="gowsYd v8Bpfb">Measure audience engagement and site statistics t…</li> from <div class="Fgvgjc">…</div> subtree intercepts pointer events
     - retrying click action
       - waiting 500ms`
then I got a `TimeoutError` after a couple of retries.

... not sure where the `Measure audience engagement and site statistics` came from, it doesn't look like google to me.

**Comment by mzxrai** [comment]
Interesting. Can you try a query like, "please go to the anthropic homepage and take a screenshot" to see if that works?

Doing a quick google on "Measure audience engagement and site statistics", it seems that that's a common string from cookie banners in the EU.
