### ISSUE TITLE
Web Search Functionality Failure

### ISSUE THREAD

**Issue by yosbeda** [mzxrai/mcp-webresearch#5]
### Environment
- **OS**: macOS Sequoia 15.2
- **Claude Desktop Version**: 0.7.5
- **MCP Web Research Version**: 0.1.6
- **Location**: Indonesia

### Problem Description
Web search consistently fails with "Page contains insufficient content" error. Could this be related to web scraping challenges, potentially involving cookie consent popups or regional restrictions?

### Steps to Reproduce
1. Attempt to use `search_google` function
2. Observe the error: "Page contains insufficient content"
3. Verify the search query works when manually searching

### Screenshots
![Screenshot 2024-12-17 at 06 48 38](https://github.com/user-attachments/assets/cf58fd71-4466-4b69-9176-440cc5fbd312)

**Comment by mzxrai** [comment]
Hi, can you please try a query like, "Please go to the anthropic homepage directly and take a screenshot"?

It would be helpful to know if the tool can navigate to sites other than Google. Thanks!

**Comment by yosbeda** [comment]
I was able to successfully visit the Anthropic homepage and take a screenshot. The page loaded without any issues, showing that the web research tool can indeed navigate to sites beyond Google. 

![Screenshot 2024-12-17 at 08 51 54](https://github.com/user-attachments/assets/56c9ec12-9c0c-4442-b7a9-a6813850ee99)

**Comment by mzxrai** [comment]
Hi @yosbeda, interesting, thanks for checking! I think the issue for Google may be that the page format is slightly different outside of the US. 

To fix this, you might have to pull down the code, run the headless browser in non-headless mode, and inspect the source to see what the issue is. Sadly I can't do that without being in your country.

**Comment by mzxrai** [comment]
Actually @yosbeda, I just pushed a new version of the server that may have a fix. 

Please quit Claude completely and then restart to try.

**Comment by yosbeda** [comment]
Hi @mzxrai, I can confirm that the web search functionality is now working flawlessly, just as it did before. 

![Screenshot 2024-12-19 at 04 36 04](https://github.com/user-attachments/assets/ab5e15ab-de0b-45c3-becf-01ac99e2a8bd)

The MCP Web Research Server is an outstanding and underappreciated alternative to MCP Brave Search, which I find limiting due to its requirement for credit card-based account creation. 

Thank you for developing this excellent project.

**Comment by mzxrai** [comment]
@yosbeda Fantastic, that is great to hear!
